// This file contains app configuration derived from package.json
// Auto-generated by scripts/update-config.js - DO NOT EDIT MANUALLY
export const APP_CONFIG = {
  version: "1.0.0",
  homepage: "https://github.com/kaiiiiiiiii/pdf-to-image"
};
