import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const packageJsonPath = path.join(__dirname, "..", "package.json");
const configPath = path.join(__dirname, "..", "src", "lib", "config.ts");

try {
  // Read package.json
  const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, "utf8"));

  // Extract version and repository URL
  const version = packageJson.version;
  const webUrl = packageJson.homepage || "https://github.com/kaiiiiiiiii/pdf-to-image";

  // Generate config.ts content
  const configContent = `// This file contains app configuration derived from package.json
// Auto-generated by scripts/update-config.js - DO NOT EDIT MANUALLY
export const APP_CONFIG = {
  version: "${version}",
  homepage: "${webUrl}"
};
`;

  // Write to config.ts
  fs.writeFileSync(configPath, configContent, "utf8");

  console.log("✅ Config updated successfully!");
  console.log(`   Version: ${version}`);
  console.log(`   Repository: ${webUrl}`);
} catch (error) {
  console.error("❌ Error updating config:", error.message);
  process.exit(1);
}
